### ISSUE TITLE
ERROR: declare: -A: invalid option

### ISSUE THREAD

**Issue by iksheth** [zakkor/shortcut#2]
when I am trying to run first time on my mac OS. It's trowing me this error. 

/usr/local/bin/shortcut: line 5: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
readlink: illegal option -- m
usage: readlink [-n] [file ...]

**Comment by iksheth** [comment]
Is this utility unix/linux specific ?

**Comment by zakkor** [comment]
`declare -A` declares an associative array in bash, which is available since version 4 of bash, I think. what version of bash have you got on macOS?

**Comment by iksheth** [comment]
Okay. I am using zsh on mac system. Is there any way we can make this for macOS ?

**Comment by zakkor** [comment]
It should be working on zsh, regardless of which OS you're on. are you sure you're using zsh? https://askubuntu.com/questions/590899/how-do-i-check-which-shell-i-am-using

**Comment by iksheth** [comment]
Yes I am using zsh. 
```
~ ❯
~ ❯
~ ❯ echo $SHELL
/bin/zsh
~ ❯ $SHELL --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
~ ❯
```

**Comment by zakkor** [comment]
Sorry, I'm not sure why it doesn't work in this case :(
I don't have access to a macOS machine to be able to test it.
Basically the only requirement is that `declare -A` works in your shell, which as far as I know, should be working in zsh. I'm not sure why zsh on macOS seems to be an exception
Let me know if you manage to figure it out though.

**Comment by iksheth** [comment]
No worries. Thank you so much for your quick response. It's great tool to use. Any one please let me know if they are aware of how I can run this tool on mac ? 

Thanks.
