### ISSUE TITLE
How to get woking on a mac

### ISSUE THREAD

**Issue by sdondley** [zakkor/shortcut#3]
If you are reading this, it probably means you are trying to install on a mac. It won't work. But you can get it to work with a few relatively simple steps.

First, if you are trying to install with install.sh and getting an error about a directory not existing, do this:

`sudo mkdir /usr/local/bin`

Now run the install script and it should work.

Now you will get more errors. The first error is because you may be running the ancient version of bash that is installed on your mac. East fix:

0) install homebrew if not already installed (google it)
1) `brew install bash`

Ok, done.

But you will still get errors because the shortcut script is set up to use the old version of bash. Easy fix:

1) Edit the first line of /usr/local/bin/shortcut to this:

`#!/usr/bin/env bash`

Ok, fixed.

But wait, don't close out the file yet. Change line 17 (or thereabouts) of the same file from:

`path=$(readlink -m $2)`

to:

`path=$(realpath -m $2)`

Everything should now work.

**Comment by sdondley** [comment]
I'll submit a proper patch when I have a little more time if there is interest. Let me know.

**Comment by zakkor** [comment]
@sdondley Looks like neither `readlink` nor `realpath` will actually work straight out of the box on macOS: one is provided by default but doesn't do what we want, and the other is not provided by default and is found in the GNU coreutils instead.

I've just pushed an update in https://github.com/zakkor/shortcut/commit/ab59224c5653b2d299ca1ef6fbb42777e01a030a
which should fix this to work on all platforms, and I've added separate scripts and installation scripts for zsh/bash (zsh is now the default on macOS)

So, after these updates, the way to install on macOS would be to just do `zsh install.zsh`, and everything should just work

**Comment by sdondley** [comment]
I have brew's coreutils package installed on my mac. That package may have installed realpath on my machine for with that package, I'm not sure. So coreutils from brew may need to be installed if that's the case.

**Comment by zakkor** [comment]
Should work out of the box on mac now. Feel free to reopen if any issues are spotted
